config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lists do
  	resources :items do
  	  member do
  	    patch :complete
  	  end
    end
  end

  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  validates :content, presence: true
  validates :list_id, presence: true

  def completed?
    !completed_at.blank?
  end
end

app/models/list.rb
class List < ApplicationRecord
	has_many :items, dependent: :destroy
	belongs_to :user

	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :set_list
	before_action :set_item, except: [:create]
	
  def create
    @item = @list.items.create(item_params)
    redirect_to list_path(@list)
  end

  def destroy
  	if @item.destroy
      flash[:success] = "Item was deleted."
    else
      flash[:error] = "Item was not deleted."
    end
    redirect_to @list
  end

  def complete
    @item.update_attribute(:completed_at, Time.now)
    redirect_to @list, notice: "Item completed"
  end

  private

    def set_item
      @item = @list.items.find(params[:id])
    end

    def set_list
      @list = List.find(params[:list_id])
    end

    def item_params
      params.require(:item).permit(:content)
    end
  
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = @user.lists.create(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_completed.html.erb
<div class="complete">
      <%= link_to "Mark as complete", complete_list_item_path(@list, item), method: :patch %>
  </div>
  <div class="item">
    <p style="opacity: 0.4;"><strike><%= item.content %></strike></p>
  </div>
  <div class="trash">
    <%= link_to 'Delete', list_item_path(@list, item), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_for([@list, @list.items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New item" %>
  <%= f.submit %>
<% end %>

app/views/items/_item.html.erb
<div class="row clearfix">
  <% if item.completed? %>

    <div class="complete">
      <%= link_to complete_list_item_path(@list, item.id), method: :patch do %>
      	<i style="opacity: 0.4;" class="fa fa-check"></i>
      <% end %>
    </div>
    <div class="item">
      <p style="opacity: 0.4;"><strike><%= item.content %></strike></p>
    </div>
    <div class="trash">
      <%= link_to list_item_path(@list, item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
   
  <% else %>

    <div class="complete">
      <%= link_to complete_list_item_path(@list, item.id), method: :patch do %>
      	<i class="fa fa-check"></i>
      <% end %>
    </div>
    <div class="item">
      <p><%= item.content %></p>
    </div>
    <div class="trash">
      <%= link_to list_item_path(@list, item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
   
  <% end %>

</div>

app/views/items/_not_completed.html.erb
<div class="complete">
      <%= link_to "Mark as complete", complete_list_item_path(@list, @item.id), method: :patch %>
  </div>
  <div class="item">
    <p><%= item.content %></p>
  </div>
  <div class="trash">
    <%= link_to 'Delete', list_item_path(@list, @item.id), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Liszts.io</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "New List", new_list_path %></li>
          <li><%= link_to "My lists", lists_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Cancel', lists_path %>

app/views/lists/index.html.erb
<% if user_signed_in? %>
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1" id="index-page">
      <div class="row">
        <h1 class="text-center" id="index-title">Lists</h1>
          <div class="title-spacing">
          <div class="col-xs-4 list-boxes" id="new-list"> 
            <%= link_to 'New List', new_list_path %>
            <div class="title text-center">New list</div>
            <div class="text-center"><i class="glyphicon glyphicon-plus-sign" id="new-list-button"></i></div>
          </div>
          <% if current_user.lists.count > 0 %>
            <% current_user.lists.reverse.each do |list| %>
              <div class="col-xs-4 list-boxes text-center"> 
                <%= link_to list.title, list %>
                <div class="title"><%= list.title %></div>
                <div id="items-left-description"><%= pluralize list.items.count, "item"%> on this list</div>
              </div>
            <% end %>
          <% end %>
          </div>
      </div> 
    </div>
  </div>
</div>
<% else %>
  <div class="container">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1" id="index-page">
        <div class="row">
          <h1 class="text-center" id="index-title">Liszts</h1>
          <h3 class="text-center">
            <%= link_to "Log in", new_user_session_path %> or <%= link_to "sign up", new_user_registration_path %> to get started.
          </h3>
        </div>
      </div>
    </div>  
  </div>
<% end %>  

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<div id="items_wrapper">
  <%= render @list.items %>
  <div id="form">
    <%= render "items/form" %>
  </div>
</div>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Delete', list_path(@list), method: :delete, data: { confirm: "Are you sure?" } %> |
<%= link_to 'Back', lists_path %>